[package]
name = "chessian"
version = "0.1.0"
edition = "2024"

[dependencies]
chess = "3.2.0"
macroquad = "0.4.14"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "perft"
harness = false
